### ISSUE TITLE
Problem with Japanese abbreviations.

### ISSUE THREAD

**Issue by LukaszKrawczyk** [foretagsplatsen/Numeral-js#9]
I've already reported this issue here adamwdraper/Numeral-js/issues/248, but as the original branch is not maintained anymore, I think it would be better to focus on your branch.

Now, Numeral.js is grouping numbers into 4 groups: thousands, milions, billions and trillions. 

But, in case of Japanese (and I suppose it also applies to Chinese) numbers are grouped in slightly different way: every **hundred**, **thousand** and **ten thousand**.
```
100 -> 1百
1,000 -> 1千
10,000 -> 1万
100,000 -> 10万
1,000,000 -> 1百万
10,000,000 -> 1千万
100,000,000 -> 1億
```
Before I start fixing this issue, I'd like to discuss how to approach that problem.
Ideas:
- add more abbreviations in library core
- let languages define their own formatting/unformatting functions

Sample formatting function here: http://jsfiddle.net/tuknLbz8/1/

Anyway, I think we need more flexible architecture if we want to support even more complicated numeral systems like [Indian numbering system](http://en.wikipedia.org/wiki/Indian_numbering_system).

**Comment by BenjaminVanRyseghem** [comment]
I think the global approach is to have everything defined at a language level.

I do agree with you that we need a more flexible approach (that's why we started to move things on languages)

Feel free to propose a PR :smile_cat:

**Comment by BenjaminVanRyseghem** [comment]
Can you please move this issue to `numbro` [here](https://github.com/foretagsplatsen/numbro/issues)

**Comment by LukaszKrawczyk** [comment]
:+1:  OK! I will move it and try to solve this issue during next week.
